services:
  devcontainer:
    # added the platform flag to override any local settings since this image is only compatible with linux/amd64.
    platform: linux/amd64
    build:
      context: .
      args:
        REPO_NAME: local-files-fastapi
    # You can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/local-files-fastapi:cached
      # Break out the venv folder as a separate docker volume for better performance on Windows hosts
      - python_venv:/workspaces/local-files-fastapi/.venv
    command: sleep infinity
    ports:
      - "51313:2222"
    environment:
      - AWS_PROFILE=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}


volumes:
  python_venv: {}
